modLoader="javafml"
loaderVersion="[1,)"
license="MIT License https://github.com/bl4ckscor3/SuspiciousZombification/blob/1.20.4/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/SuspiciousZombification/issues"

[[mods]]
	modId="suszombification"
	version="${file.jarVersion}"
	displayName="Suspicious Zombification"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious-zombification"
	authors="Redstone_Dubstep, bl4ckscor3"
	description='''A mod about zombifying animals, fighting off the zombie's curse, eating suspicious pies, and benefiting from their effects.'''

[[dependencies.suszombification]]
	modId="neoforge"
	type="required"
	versionRange="[20.4.40-beta,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.suszombification]]
	modId="minecraft"
	type="required"
	versionRange="[1.20.4,1.21)"
	ordering="NONE"
	side="BOTH"
