modLoader="javafml"
loaderVersion="[40,)"
license="MIT License https://github.com/bl4ckscor3/SuspiciousZombification/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/SuspiciousZombification/issues"

[[mods]]
	modId="suszombification"
	version="${file.jarVersion}"
	displayName="Suspicious Zombification"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious-zombification"
	authors="Redstone_Dubstep, bl4ckscor3"
	description='''A mod about zombifying animals, fighting off the zombie's curse, eating suspicious pies, and benefiting from their effects.'''

[[dependencies.suszombification]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.suszombification]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18,1.19)"
	ordering="NONE"
	side="BOTH"
