modLoader="javafml"
loaderVersion="[37,)"
license="MIT License https://github.com/bl4ckscor3/SuspiciousZombification/blob/1.17/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/SuspiciousZombification/issues"

[[mods]] 
	modId="suszombification"
	version="${file.jarVersion}"
	displayName="Suspicious Zombification"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious-zombification"
	authors="Redstone_Dubstep, bl4ckscor3"
	description='''
	'''

[[dependencies.suszombification]]
	modId="forge"
	mandatory=true
	versionRange="[37,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.suszombification]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.17.1,1.18)"
	ordering="NONE"
	side="BOTH"
